version: '3.7'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - network
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '9000:8080'
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - network
  server:
    image: 'server'
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    depends_on:
      - kafka
    networks:
      - network
  car_1:
    image: 'client'
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8081:8081'
    environment:
      APP_SERVER_ADDRESS: 'server:8080'
      CAR_IMEI: 'ccbfa71e-2d26-47bd-b72b-d57a29f9e878'
    depends_on:
      - server
    networks:
      - network
  car_2:
    image: 'client'
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8082:8082'
    environment:
      APP_SERVER_ADDRESS: 'server:8080'
      CAR_IMEI: '8c2d7c19-42ff-414b-8f93-600d0abb0c13'
    depends_on:
      - server
    networks:
      - network
  car_3:
    image: 'client'
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8083:8083'
    environment:
      APP_SERVER_ADDRESS: 'server:8080'
      CAR_IMEI: 'a801d3b5-d44c-4b8a-a622-6c52102db013'
    depends_on:
      - server
    networks:
      - network

networks:
  network:
    driver: bridge